
FROM python:3.9-alpine

# Set the working directory
WORKDIR /app

COPY app.py config.txt /app/
RUN pip install Flask

# Expose port 5000 for the web service
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
